import type { CatalogCourse } from "./types";

export const CATALOG: CatalogCourse[] = [
  {
    code: "SCIE 001",
    title: "Science One",
    credits: 27,
    tags: ["scie001"],
    blurb:
      "An integrated first-year stream covering biology, chemistry, physics, and math together. Completing it usually satisfies eligibility instead of the separate course list.",
  },
  {
    code: "SCIE 113",
    title: "First-Year Seminar in Science",
    credits: 3,
    tags: ["comms"],
    blurb: "Small-group writing and discussion about how science is done. Common communication requirement, not usually an eligibility course.",
  },
  {
    code: "WRDS 150",
    title: "Writing and Research in the Disciplines",
    credits: 3,
    tags: ["comms"],
    blurb: "Academic writing and research methods. Another way to meet the first-year communication requirement.",
  },
  {
    code: "MATH 100",
    title: "Differential Calculus",
    credits: 3,
    tags: ["math"],
    blurb: "The usual Term 1 calculus: limits, derivatives, and applications. Most Science students take this or an approved equivalent.",
  },
  {
    code: "MATH 110",
    title: "Differential Calculus (extended)",
    credits: 6,
    tags: ["math"],
    blurb: "Differential calculus stretched over two terms with extra support. Counts as the MATH 100 equivalent if you need a slower start.",
  },
  {
    code: "MATH 120",
    title: "Honours Differential Calculus",
    credits: 4,
    tags: ["math"],
    blurb: "A proof-leaning Term 1 calculus for students aiming at honours math or a stronger theory base.",
  },
  {
    code: "MATH 180",
    title: "Differential Calculus with Physical Applications",
    credits: 4,
    tags: ["math"],
    blurb: "Differential calculus aimed at physical-science applications. An approved MATH 100 equivalent.",
  },
  {
    code: "MATH 101",
    title: "Integral Calculus",
    credits: 3,
    tags: ["math"],
    blurb: "The usual Term 2 calculus: integrals, series, and applications. Required to apply for several math-heavy majors.",
  },
  {
    code: "MATH 121",
    title: "Honours Integral Calculus",
    credits: 4,
    tags: ["math"],
    blurb: "Honours follow-up to MATH 120. Counts as the MATH 101 equivalent.",
  },
  {
    code: "CHEM 111",
    title: "Structure, Bonding and Equilibrium",
    credits: 4,
    tags: ["chem"],
    blurb: "Term 1 chemistry for students without Chemistry 12 (or who need a gentler start). Pair it with CHEM 123.",
  },
  {
    code: "CHEM 121",
    title: "Structure and Bonding in Chemistry",
    credits: 4,
    tags: ["chem"],
    blurb: "The standard Term 1 chemistry lecture + lab for students who completed Chemistry 12.",
  },
  {
    code: "CHEM 141",
    title: "Structure and Bonding (enriched)",
    credits: 4,
    tags: ["chem"],
    blurb: "An enriched Term 1 chemistry option. Counts as the CHEM 121 equivalent.",
  },
  {
    code: "CHEM 123",
    title: "Thermodynamics, Kinetics and Organic Chemistry",
    credits: 4,
    tags: ["chem"],
    blurb: "Term 2 chemistry. Needed for most life-science and chemistry specializations.",
  },
  {
    code: "BIOL 111",
    title: "Introduction to Modern Biology",
    credits: 3,
    tags: ["biol"],
    blurb: "A survey biology course if you did not take Biology 11/12. Not a substitute for BIOL 112 when that is required.",
  },
  {
    code: "BIOL 112",
    title: "Biology of the Cell",
    credits: 3,
    tags: ["biol"],
    blurb: "Cell biology, often in Term 1 or 2. The usual eligibility biology for life-science majors.",
  },
  {
    code: "BIOL 121",
    title: "Genetics, Evolution and Ecology",
    credits: 3,
    tags: ["biol"],
    blurb: "Organismal biology: genetics, evolution, and ecology. Some majors accept this instead of BIOL 112.",
  },
  {
    code: "BIOL 140",
    title: "Laboratory Investigations in Life Science",
    credits: 2,
    tags: ["biol"],
    blurb: "First-year biology lab. Useful for later BIOL courses, but not always on the eligibility list.",
  },
  {
    code: "PHYS 100",
    title: "Introductory Physics",
    credits: 3,
    tags: ["phys"],
    blurb: "A preparatory physics course if your high-school physics is light. Some programs accept it as one physics option.",
  },
  {
    code: "PHYS 108",
    title: "Enriched Physics II",
    credits: 3,
    tags: ["phys"],
    blurb: "Enriched electricity, light, and radiation. Pair with PHYS 119 when a physics lab is required.",
  },
  {
    code: "PHYS 117",
    title: "Dynamics and Waves",
    credits: 3,
    tags: ["phys"],
    blurb: "Mechanics and waves for Science students. A common first-term physics lecture.",
  },
  {
    code: "PHYS 118",
    title: "Electricity, Light and Radiation",
    credits: 3,
    tags: ["phys"],
    blurb: "The usual second physics lecture. Often paired with PHYS 119 for lab credit.",
  },
  {
    code: "PHYS 119",
    title: "Experimental Physics Lab",
    credits: 1,
    tags: ["phys"],
    blurb: "The Science physics lab that goes with PHYS 108 or PHYS 118 when a lab is required.",
  },
  {
    code: "PHYS 131",
    title: "Energy and Waves",
    credits: 3,
    tags: ["phys"],
    blurb: "An introductory physics lecture used in several first-year timetables and as a physics option.",
  },
  {
    code: "PHYS 157",
    title: "Introductory Physics for Engineers I",
    credits: 3,
    tags: ["phys"],
    blurb: "Engineering stream mechanics. Sometimes accepted as a physics lecture option.",
  },
  {
    code: "PHYS 158",
    title: "Introductory Physics for Engineers II",
    credits: 3,
    tags: ["phys"],
    blurb: "Engineering electricity and waves. Pair with PHYS 159 if you use the engineering physics path.",
  },
  {
    code: "PHYS 159",
    title: "Introductory Physics Laboratory",
    credits: 1,
    tags: ["phys"],
    blurb: "Engineering physics lab. Counts with PHYS 158 for the engineering physics eligibility path.",
  },
  {
    code: "CPSC 103",
    title: "Introduction to Systematic Program Design",
    credits: 3,
    tags: ["cpsc"],
    blurb: "A gentler first programming course. Data Science accepts it; Computer Science major eligibility is CPSC 110 or CPSC 107 instead.",
  },
  {
    code: "CPSC 107",
    title: "Systematic Program Design",
    credits: 3,
    tags: ["cpsc"],
    blurb: "The CPSC 110 equivalent for students who already completed CPSC 103. Do not take both 107 and 110.",
  },
  {
    code: "CPSC 110",
    title: "Computation, Programs, and Programming",
    credits: 4,
    tags: ["cpsc"],
    blurb: "The main first-year CS course. Required (or CPSC 107) to apply to Computer Science and most CS combined majors.",
  },
  {
    code: "CPSC 121",
    title: "Models of Computation",
    credits: 4,
    tags: ["cpsc"],
    blurb: "Discrete math and computation. Strongly recommended in first year for CS, but not the eligibility gate.",
  },
  {
    code: "DSCI 100",
    title: "Introduction to Data Science",
    credits: 3,
    tags: ["dsci", "stat"],
    blurb: "Data wrangling, visualization, and basic inference in R. Eligibility for Data Science; also a STAT 200 alternative for some stats programs.",
  },
  {
    code: "STAT 200",
    title: "Elementary Statistics for Applications",
    credits: 3,
    tags: ["stat"],
    blurb: "Intro statistics. Some statistics specializations accept this instead of DSCI 100.",
  },
  {
    code: "ECON 101",
    title: "Principles of Microeconomics",
    credits: 3,
    tags: ["econ"],
    blurb: "Markets, prices, and individual decisions. Required with ECON 102 for Statistics and Economics.",
  },
  {
    code: "ECON 102",
    title: "Principles of Macroeconomics",
    credits: 3,
    tags: ["econ"],
    blurb: "Inflation, unemployment, and the broader economy. Pair with ECON 101 for the combined major.",
  },
  {
    code: "EOSC 110",
    title: "The Solid Earth",
    credits: 3,
    tags: ["eosc"],
    blurb: "Rocks, plate tectonics, and the solid Earth. Typical first-year Earth-science elective.",
  },
  {
    code: "EOSC 112",
    title: "The Fluid Earth",
    credits: 3,
    tags: ["eosc"],
    blurb: "Oceans, atmosphere, and climate. A common first-year Earth-science elective.",
  },
  {
    code: "PSYC 101",
    title: "Introduction to Biological and Cognitive Psychology",
    credits: 3,
    tags: ["psyc"],
    blurb: "Brain, mind, and behaviour. Useful background for Neuroscience; not always on the eligibility list.",
  },
  {
    code: "LING 100",
    title: "Introduction to Language and Linguistics",
    credits: 3,
    tags: ["ling"],
    blurb: "How language is structured. Relevant later for Cognitive Systems, not a first-year eligibility gate.",
  },
];

export function courseByCode(code: string): CatalogCourse | undefined {
  return CATALOG.find((c) => c.code === code);
}
