import type { Requirement, Specialization } from "./types";

const chem = (): Requirement => ({
  kind: "all",
  items: [
    { kind: "any", courses: ["CHEM 111", "CHEM 121", "CHEM 141"] },
    { kind: "any", courses: ["CHEM 123"] },
  ],
});

const biol112 = (): Requirement => ({ kind: "any", courses: ["BIOL 112"] });
const biol112or121 = (): Requirement => ({
  kind: "any",
  courses: ["BIOL 112", "BIOL 121"],
});
const diffCalc = (): Requirement => ({
  kind: "any",
  courses: ["MATH 100", "MATH 110", "MATH 120", "MATH 180"],
});
const integral = (): Requirement => ({
  kind: "any",
  courses: ["MATH 101", "MATH 121"],
});
const cpsc = (): Requirement => ({
  kind: "any",
  courses: ["CPSC 107", "CPSC 110"],
});
const cpsc103or110 = (): Requirement => ({
  kind: "any",
  courses: ["CPSC 103", "CPSC 110"],
});
const physLab = (): Requirement => ({
  kind: "or",
  items: [
    {
      kind: "all",
      items: [
        { kind: "any", courses: ["PHYS 108", "PHYS 118"] },
        { kind: "any", courses: ["PHYS 119"] },
      ],
    },
    {
      kind: "all",
      items: [
        { kind: "any", courses: ["PHYS 158"] },
        { kind: "any", courses: ["PHYS 159"] },
      ],
    },
  ],
});
const physAny = (): Requirement => ({
  kind: "any",
  courses: ["PHYS 100", "PHYS 108", "PHYS 117", "PHYS 118", "PHYS 131", "PHYS 157", "PHYS 158"],
});
const dsciOrStat = (): Requirement => ({
  kind: "any",
  courses: ["DSCI 100", "STAT 200"],
});

function withScie(req: Requirement): Requirement {
  return { kind: "or", items: [{ kind: "scie001" }, req] };
}

const Y = (year: number, value: number | "NF" | "sup" | null) => ({ year, value });

const coreFirstYear = [
  "MATH 100",
  "MATH 101",
  "CHEM 121",
  "CHEM 123",
  "SCIE 113",
];

export const SPECIALIZATIONS: Specialization[] = [
  {
    id: "cpsc",
    name: "Computer Science",
    kind: "major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie(cpsc()),
    notes: [
      "CPSC 110 or CPSC 107 is the eligibility course. CPSC 121 is strongly recommended in first year.",
      "Computer Science specializations sit under a faculty-wide umbrella quota. You may rank at most two CS-umbrella choices.",
    ],
    recommended: ["CPSC 110", "CPSC 121", "MATH 100", "MATH 101", "SCIE 113", "DSCI 100"],
    cutoffs: [Y(2022, 81.6), Y(2023, 83.5), Y(2024, 82.6), Y(2025, 78.9), Y(2026, 76.5)],
  },
  {
    id: "nsci",
    name: "Neuroscience",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112()] }),
    notes: [
      "A small share of seats may go to applicants slightly below the cutoff.",
    ],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121", "PSYC 101"],
    cutoffs: [Y(2022, 79.2), Y(2023, 81.4), Y(2024, 78.2), Y(2025, 81.0), Y(2026, 82.4)],
  },
  {
    id: "pcth",
    name: "Pharmacology",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112()] }),
    notes: [],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121"],
    cutoffs: [Y(2022, 85.4), Y(2023, 85.5), Y(2024, 83.5), Y(2025, 80.8), Y(2026, 78.7)],
  },
  {
    id: "mbim",
    name: "Microbiology and Immunology",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112()] }),
    notes: [],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121", "BIOL 140"],
    cutoffs: [Y(2022, 81.7), Y(2023, 82.2), Y(2024, 78.9), Y(2025, 77.5), Y(2026, 79.2)],
  },
  {
    id: "bioc",
    name: "Biochemistry",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112(), diffCalc()] }),
    notes: [],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121"],
    cutoffs: [Y(2022, 71.0), Y(2023, 76.4), Y(2024, 65.9), Y(2025, 76.7), Y(2026, 76.5)],
  },
  {
    id: "caps",
    name: "Cellular, Anatomical and Physiological Sciences",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112()] }),
    notes: [],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121"],
    cutoffs: [Y(2024, 85.6), Y(2025, 83.7), Y(2026, 77.3)],
  },
  {
    id: "biol",
    name: "Biology",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112or121()] }),
    notes: ["Quota has not filled in recent years — all eligible applicants were admitted."],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121", "BIOL 140"],
    cutoffs: [Y(2022, "NF"), Y(2023, "NF"), Y(2024, "NF"), Y(2025, "NF"), Y(2026, "NF")],
  },
  {
    id: "chem",
    name: "Chemistry",
    kind: "major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), integral()] }),
    notes: ["Quota has not filled in recent years."],
    recommended: [...coreFirstYear, "PHYS 117", "PHYS 118"],
    cutoffs: [Y(2022, "NF"), Y(2023, "NF"), Y(2024, "NF"), Y(2025, "NF"), Y(2026, "NF")],
  },
  {
    id: "dsci",
    name: "Data Science",
    kind: "major",
    quota: true,
    eligibility: withScie({
      kind: "all",
      items: [diffCalc(), { kind: "any", courses: ["DSCI 100"] }, cpsc103or110()],
    }),
    notes: [
      "CPSC 103 and DSCI 100 can be finished by the end of Summer Term 1.",
      "A small number of seats go to applicants slightly below the cutoff who ranked Data Science highly.",
    ],
    recommended: ["MATH 100", "MATH 101", "DSCI 100", "CPSC 103", "CPSC 110", "SCIE 113"],
    cutoffs: [Y(2025, 76.0), Y(2026, 77.4)],
  },
  {
    id: "stat",
    name: "Statistics",
    kind: "major",
    quota: true,
    umbrella: "statistics",
    eligibility: withScie({ kind: "all", items: [integral(), dsciOrStat()] }),
    notes: [],
    recommended: ["MATH 100", "MATH 101", "DSCI 100", "CPSC 110", "SCIE 113"],
    cutoffs: [Y(2022, 77.5), Y(2023, 78.7), Y(2024, 78.1), Y(2025, 70.4), Y(2026, 57.0)],
  },
  {
    id: "math",
    name: "Mathematics",
    kind: "major",
    quota: true,
    eligibility: withScie(integral()),
    notes: [
      "Admission uses both sessional average and MATH course average from 2024 onward.",
    ],
    recommended: ["MATH 100", "MATH 101", "CPSC 110", "PHYS 117", "SCIE 113"],
    cutoffs: [Y(2022, 69.1), Y(2023, 76.3), Y(2024, 67.0), Y(2025, "NF"), Y(2026, 61.0)],
  },
  {
    id: "masc",
    name: "Mathematical Sciences",
    kind: "major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), integral()] }),
    notes: ["Sub-quota inside the Computer Science and Statistics umbrellas."],
    recommended: ["CPSC 110", "CPSC 121", "MATH 100", "MATH 101", "DSCI 100"],
    cutoffs: [Y(2022, 85.4), Y(2025, 81.8), Y(2026, 81.1)],
  },
  {
    id: "cogs-brain",
    name: "Cognitive Systems: Cognition and Brain",
    kind: "major",
    quota: true,
    umbrella: "cognitive-systems",
    eligibility: { kind: "none" },
    notes: ["No specific first-year eligibility courses."],
    recommended: ["CPSC 110", "MATH 100", "PSYC 101", "SCIE 113", "LING 100"],
    cutoffs: [Y(2022, 77.3), Y(2023, 79.2), Y(2024, 77.4), Y(2025, 73.3), Y(2026, 73.9)],
  },
  {
    id: "cogs-cid",
    name: "Cognitive Systems: Computational Intelligence and Design",
    kind: "major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie(cpsc()),
    notes: ["Sub-quota inside Computer Science and Cognitive Systems."],
    recommended: ["CPSC 110", "CPSC 121", "MATH 100", "MATH 101", "SCIE 113"],
    cutoffs: [Y(2022, 81.8), Y(2023, 84.6), Y(2024, 84.0), Y(2025, 83.0), Y(2026, 83.1)],
  },
  {
    id: "ensc",
    name: "Environmental Sciences",
    kind: "major",
    quota: true,
    eligibility: { kind: "none" },
    notes: ["No specific eligibility courses. Quota has not filled recently."],
    recommended: [...coreFirstYear, "BIOL 121", "EOSC 110"],
    cutoffs: [Y(2022, 67.6), Y(2023, 70.3), Y(2024, "NF"), Y(2025, "NF"), Y(2026, "NF")],
  },
  {
    id: "insc",
    name: "Integrated Sciences",
    kind: "major",
    quota: true,
    eligibility: { kind: "none" },
    notes: ["How highly you rank Integrated Sciences is part of the decision from 2024 onward."],
    recommended: [...coreFirstYear, "BIOL 112", "CPSC 103"],
    cutoffs: [Y(2022, "NF"), Y(2023, 80.1), Y(2024, 65.5), Y(2025, 79.5), Y(2026, 82.2)],
  },
  {
    id: "phys",
    name: "Physics",
    kind: "major",
    quota: false,
    eligibility: withScie({ kind: "all", items: [integral(), physLab()] }),
    notes: ["No quota: eligible students are admitted."],
    recommended: ["MATH 100", "MATH 101", "PHYS 117", "PHYS 118", "PHYS 119", "SCIE 113"],
    cutoffs: [],
  },
  {
    id: "astr",
    name: "Astronomy",
    kind: "major",
    quota: false,
    eligibility: withScie({ kind: "all", items: [integral(), physLab()] }),
    notes: ["No quota: eligible students are admitted."],
    recommended: ["MATH 100", "MATH 101", "PHYS 117", "PHYS 118", "PHYS 119"],
    cutoffs: [],
  },
  {
    id: "atsc",
    name: "Atmospheric Science",
    kind: "major",
    quota: false,
    eligibility: withScie({ kind: "all", items: [integral(), physLab()] }),
    notes: ["No quota: eligible students are admitted."],
    recommended: ["MATH 100", "MATH 101", "PHYS 117", "PHYS 118", "CHEM 121"],
    cutoffs: [],
  },
  {
    id: "geop",
    name: "Geophysics",
    kind: "major",
    quota: false,
    eligibility: withScie({ kind: "all", items: [integral(), physAny()] }),
    notes: ["No quota: eligible students are admitted."],
    recommended: ["MATH 100", "MATH 101", "PHYS 117", "EOSC 110"],
    cutoffs: [],
  },
  {
    id: "eosc",
    name: "Earth and Ocean Sciences",
    kind: "major",
    quota: false,
    eligibility: { kind: "none" },
    notes: ["No specific eligibility courses and no quota."],
    recommended: ["MATH 100", "CHEM 121", "EOSC 110", "EOSC 112", "SCIE 113"],
    cutoffs: [],
  },
  {
    id: "geol",
    name: "Geology",
    kind: "major",
    quota: false,
    eligibility: { kind: "none" },
    notes: ["No specific eligibility courses and no quota."],
    recommended: ["MATH 100", "CHEM 121", "CHEM 123", "EOSC 110"],
    cutoffs: [],
  },
  {
    id: "geos",
    name: "Geographical Sciences",
    kind: "major",
    quota: false,
    eligibility: { kind: "none" },
    notes: ["No specific eligibility courses and no quota."],
    recommended: ["MATH 100", "EOSC 112", "SCIE 113"],
    cutoffs: [],
  },
  {
    id: "cmsc",
    name: "Combined Major in Science",
    kind: "combined-major",
    quota: false,
    eligibility: { kind: "none" },
    notes: ["Breadth-focused. No specific eligibility courses and no quota."],
    recommended: [...coreFirstYear, "BIOL 112", "PHYS 131"],
    cutoffs: [],
  },
  {
    id: "cpsc-biol",
    name: "Computer Science and Biology",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), chem(), biol112or121()] }),
    notes: ["Sub-quota inside Computer Science. Rank at most two CS-umbrella choices."],
    recommended: ["CPSC 110", "CPSC 121", "CHEM 121", "CHEM 123", "BIOL 112", "BIOL 121"],
    cutoffs: [Y(2022, 82.1), Y(2023, 85.1), Y(2024, 91.5), Y(2025, "sup"), Y(2026, null)],
  },
  {
    id: "cpsc-math",
    name: "Computer Science and Mathematics",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), integral()] }),
    notes: [],
    recommended: ["CPSC 110", "CPSC 121", "MATH 100", "MATH 101"],
    cutoffs: [Y(2022, 82.9), Y(2023, 84.9), Y(2024, 83.5), Y(2025, 80.6), Y(2026, 77.4)],
  },
  {
    id: "cpsc-stat",
    name: "Computer Science and Statistics",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), integral()] }),
    notes: [],
    recommended: ["CPSC 110", "CPSC 121", "MATH 100", "MATH 101", "DSCI 100"],
    cutoffs: [Y(2022, 81.8), Y(2023, 84.1), Y(2024, 83.1), Y(2025, 82.0), Y(2026, 78.3)],
  },
  {
    id: "cpsc-phys",
    name: "Computer Science and Physics",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), integral(), physLab()] }),
    notes: [],
    recommended: ["CPSC 110", "MATH 100", "MATH 101", "PHYS 117", "PHYS 118", "PHYS 119"],
    cutoffs: [Y(2022, 87.7), Y(2023, 84.6), Y(2024, 84.9), Y(2025, 82.6), Y(2026, 77.7)],
  },
  {
    id: "cpsc-chem",
    name: "Computer Science and Chemistry",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), chem(), integral()] }),
    notes: [],
    recommended: ["CPSC 110", "CHEM 121", "CHEM 123", "MATH 100", "MATH 101"],
    cutoffs: [Y(2024, 87.5), Y(2026, 79.1)],
  },
  {
    id: "cpsc-mbim",
    name: "Computer Science and Microbiology and Immunology",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), chem(), biol112()] }),
    notes: ["Sub-quota inside Computer Science."],
    recommended: ["CPSC 110", "CHEM 121", "CHEM 123", "BIOL 112"],
    cutoffs: [Y(2022, 81.6), Y(2023, 84.0), Y(2024, 85.9), Y(2026, 85.4)],
  },
  {
    id: "cpsc-nsci",
    name: "Computer Science and Neuroscience",
    kind: "combined-major",
    quota: true,
    umbrella: "computer-science",
    eligibility: withScie({ kind: "all", items: [cpsc(), chem(), biol112()] }),
    notes: ["New for 2026."],
    recommended: ["CPSC 110", "CHEM 121", "CHEM 123", "BIOL 112"],
    cutoffs: [Y(2026, 88.4)],
  },
  {
    id: "stat-econ",
    name: "Statistics and Economics",
    kind: "combined-major",
    quota: true,
    umbrella: "statistics",
    eligibility: withScie({
      kind: "all",
      items: [
        integral(),
        dsciOrStat(),
        { kind: "any", courses: ["ECON 101"] },
        { kind: "any", courses: ["ECON 102"] },
      ],
    }),
    notes: [
      "For 2026 only, missing ECON 101/102 could still lead to conditional admission.",
    ],
    recommended: ["MATH 100", "MATH 101", "DSCI 100", "ECON 101", "ECON 102"],
    cutoffs: [],
  },
  {
    id: "bioc-chem",
    name: "Biochemistry and Chemistry",
    kind: "combined-major",
    quota: true,
    eligibility: withScie({ kind: "all", items: [chem(), biol112(), integral()] }),
    notes: [],
    recommended: [...coreFirstYear, "BIOL 112"],
    cutoffs: [Y(2022, 68.8), Y(2023, 73.7), Y(2024, 73.5), Y(2025, 76.7), Y(2026, 90.5)],
  },
  {
    id: "chem-biol",
    name: "Chemical Biology",
    kind: "combined-major",
    quota: true,
    eligibility: withScie({
      kind: "all",
      items: [chem(), biol112or121(), diffCalc()],
    }),
    notes: ["Quota has not filled recently."],
    recommended: [...coreFirstYear, "BIOL 112", "BIOL 121"],
    cutoffs: [Y(2022, 73.4), Y(2023, 65.9), Y(2024, "NF"), Y(2025, "NF"), Y(2026, "NF")],
  },
];

export function specializationById(id: string): Specialization | undefined {
  return SPECIALIZATIONS.find((s) => s.id === id);
}
